spring:
  application:
    name: api-erp
  datasource:
    url: jdbc:sqlserver://192.168.1.39:1433;databaseName=bd_gemini;encrypt=true;trustServerCertificate=true
    username: sa
    password: B3t026082006!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
  profiles:
    active: dev
  server:
    address: 0.0.0.0
    port: 8080
jwt:
  secret: "XCCH0gQYcPvw2RLXzCrUndXos92Vv9FO3pCEoCChQe+1x8+1VBdSSy9Tezrhl+QPx0dzCs8KLxLfhrHMRq4Fnw=="